name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package (with benchmark extras)
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[benchmark]
          python -m pip install pytest
      - name: Run tests
        run: |
          pytest -q

